msi_page_show:
    pattern: /{_locale}/{slug}
    defaults: { _controller: MsiCmsBundle:Page:show, slug: ~ }
    requirements:
        _locale: fr|en

msi_cms_menu_node_admin_sort:
    pattern: /admin/menu-node/sort.html
    defaults: { _controller: MsiCmsBundle:MenuNode:sort, _admin: msi_cms_menu_node_admin }
