Msi\CmsBundle\Entity\MenuTranslation:
    properties:
        name:
            - NotBlank: ~

Msi\CmsBundle\Entity\Page:
    properties:
        template:
            - NotBlank: ~

Msi\CmsBundle\Entity\PageTranslation:
    properties:
        title:
            - NotBlank: ~

Msi\CmsBundle\Entity\Site:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: host
    properties:
        host:
            - NotBlank: ~

Msi\CmsBundle\Entity\Block:
    properties:
        name:
            - NotBlank: ~

Msi\CmsBundle\Entity\Email:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        fromWho:
            - NotBlank: ~
            - Email: ~
        toWho:
            - NotBlank: ~
            - Email: ~

Msi\CmsBundle\Entity\EmailTranslation:
    properties:
        subject:
            - NotBlank: ~
        body:
            - NotBlank: ~
